# Generated by Django 6.1 on 2026-08-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='contact_method',
            field=models.CharField(choices=[('phone', 'تماس تلفنی'), ('telegram', 'تلگرام')], default='phone', max_length=10, verbose_name='روش تماس'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='آیدی تلگرام'),
        ),
    ]
