# Generated by Django 6.1 on 2026-08-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmessage_contact_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('in_progress', 'در حال بررسی'), ('done', 'انجام شده')], default='new', max_length=20, verbose_name='وضعیت پیگیری'),
        ),
    ]
