# Generated by Django 6.1 on 2026-08-14 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactmessage_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ارسال\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='request_type',
            field=models.CharField(choices=[('agent-ai', 'ساخت Agent هوش مصنوعی'), ('automation', 'پکیج اتوماسیون آماده (n8n)'), ('mlops', 'استقرار مدل هوش مصنوعی'), ('consulting', 'مشاوره هوش مصنوعی'), ('web-design', 'طراحی وب'), ('app-development', 'طراحی اپلیکیشن'), ('education', 'آموزش'), ('other', 'سایر موارد')], max_length=20, verbose_name='نوع درخواست'),
        ),
    ]
