# Generated by Django 6.1 on 2026-08-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ (آدرس سئو-دوست)')),
                ('category', models.CharField(max_length=50, verbose_name='دسته')),
                ('icon', models.CharField(default='📝', max_length=8, verbose_name='آیکون')),
                ('gradient', models.CharField(default='135deg,#1e3a5f,#2563eb', max_length=120, verbose_name='گرادیان پس\u200cزمینه')),
                ('excerpt', models.TextField(verbose_name='خلاصه')),
                ('content', models.TextField(blank=True, verbose_name='متن کامل')),
                ('read_time', models.PositiveSmallIntegerField(default=5, verbose_name='زمان مطالعه (دقیقه)')),
                ('published_at', models.DateField(verbose_name='تاریخ انتشار')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-published_at'],
            },
        ),
    ]
