# Generated by Django 6.1 on 2026-08-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='تصویر سربرگ مقاله (اختیاری — اگر نباشد گرادیان نمایش داده می\u200cشود)', null=True, upload_to='blog_covers/', verbose_name='تصویر شاخص'),
        ),
    ]
