# Generated by Django 6.1 on 2026-08-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='شماره نمایش')),
                ('icon', models.CharField(default='🌐', max_length=8, verbose_name='آیکون')),
                ('categories', models.CharField(default='web', help_text='کلیدها با فاصله جدا می\u200cشوند، مثل: web ai', max_length=50, verbose_name='کلیدهای فیلتر')),
                ('category_label', models.CharField(max_length=50, verbose_name='برچسب دسته')),
                ('short_description', models.CharField(max_length=250, verbose_name='توضیح کوتاه کارت')),
                ('description', models.TextField(blank=True, verbose_name='توضیح کامل مودال')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='تکنولوژی\u200cها')),
                ('duration', models.CharField(blank=True, max_length=50, verbose_name='زمان اجرا')),
                ('role', models.CharField(blank=True, max_length=50, verbose_name='نقش')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='وضعیت')),
                ('github_url', models.URLField(blank=True, verbose_name='لینک GitHub')),
                ('gradient', models.CharField(default='135deg,#1e1b4b,#7c3aed', max_length=120, verbose_name='گرادیان پس\u200cزمینه')),
                ('is_published', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['order'],
            },
        ),
    ]
