# Generated by Django 6.1 on 2026-08-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='تصویر کارت و مودال (اختیاری — اگر نباشد گرادیان نمایش داده می\u200cشود)', null=True, upload_to='project_covers/', verbose_name='تصویر شاخص'),
        ),
    ]
