# Generated by Django 6.1 on 2026-08-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='کلید (شناسه)')),
                ('label', models.CharField(max_length=100, verbose_name='عنوان نمایشی')),
                ('value', models.TextField(blank=True, verbose_name='مقدار')),
                ('group', models.CharField(choices=[('home', 'صفحه اصلی'), ('contact', 'تماس'), ('about', 'درباره ما'), ('other', 'سایر')], default='other', max_length=20, verbose_name='گروه')),
                ('is_textarea', models.BooleanField(default=False, help_text='برای متن\u200cهای طولانی مثل توضیحات', verbose_name='چندخطی (textarea)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'متن سایت',
                'verbose_name_plural': 'متن\u200cهای سایت',
                'ordering': ['group', 'key'],
            },
        ),
    ]
