# Generated by Django 6.1 on 2026-08-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='مسیر')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='کلید نشست')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان بازدید')),
            ],
            options={
                'verbose_name': 'بازدید',
                'verbose_name_plural': 'بازدیدها',
                'ordering': ['-created_at'],
            },
        ),
    ]
